spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: validate
        show_sql: true
        format_sql: true
  datasource:
    username: postgres
    password: 111
    url: jdbc:postgresql://localhost:5432/qtex
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: hitapo